import "@/app/globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Inter, Orbitron } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Denny's blog",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh-TW">
      <body
        style={{
          minHeight: "100vh",
          display: "flex",
          flexDirection: "column",
        }}
      >
        <Header />
        <main style={{ flex: 1 }}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
